"use client"

import { useState, useEffect, useRef } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { User, Mail, Camera, Trash2, Save, X, AlertTriangle, ChevronDown, ChevronUp } from "lucide-react"
import Header from "@/components/header"

export default function SettingsPage() {
  const router = useRouter()
  const fileInputRef = useRef<HTMLInputElement>(null)
  
  const [user, setUser] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [name, setName] = useState("")
  const [avatar, setAvatar] = useState("")
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [deleting, setDeleting] = useState(false)
  const [error, setError] = useState("")
  const [success, setSuccess] = useState("")
  const [expandedFaq, setExpandedFaq] = useState<number | null>(null)

  const faqs = [
    {
      question: "What does the molecule analysis report include?",
      answer: "Our system aggregates insights from six AI agents—Clinical Trials, Patents, Internal Knowledge, EXIM Trade, IQVIA Insights, and Web Intelligence. Each agent contributes real-time data to create a complete repurposing report containing indications, market potential, trial status, competitive landscape, patents, regulatory alerts, and more."
    },
    {
      question: "How do the six agents work together?",
      answer: "Each agent is specialized in a specific data domain. When you enter a molecule, all agents simultaneously retrieve relevant datasets. Their findings are merged and summarized into a single, comprehensive report with automatically generated insights."
    },
    {
      question: "Where does the clinical trials and patent information come from?",
      answer: "The platform uses publicly accessible datasets, licensed databases, and proprietary knowledge sources to compile verified information on clinical trials, patents, regulatory filings, and global market activity."
    },
    {
      question: "How accurate are the insights generated by the system?",
      answer: "The agents rely on up-to-date data sources and apply structured reasoning models to identify patterns, repurposing opportunities, and market trends. While highly reliable, the insights should be used as decision support rather than medical or legal advice."
    },
    {
      question: "Can I analyze any molecule or only approved drugs?",
      answer: "You can analyze both approved drugs and investigational compounds. The agents adapt their output depending on available evidence, providing either full-scope market data or early research-stage insights."
    },
    {
      question: "How long does a molecule analysis take?",
      answer: "Most analyses are completed within 10–20 seconds. However, complex molecules requiring deep patent + clinical + external web intelligence queries may take slightly longer."
    }
  ]

  useEffect(() => {
    fetchUserData()
  }, [])

  const fetchUserData = async () => {
    try {
      const response = await fetch('/api/auth/session')
      const data = await response.json()
      
      if (data.authenticated) {
        setUser(data.user)
        setName(data.user.name)
        setAvatar(data.user.avatar || "")
      } else {
        router.push('/login')
      }
    } catch (err) {
      console.error('Failed to fetch user:', err)
      setError('Failed to load user data')
    } finally {
      setLoading(false)
    }
  }

  const refreshHeader = () => {
    // Dispatch custom event to notify header
    window.dispatchEvent(new CustomEvent('userUpdated', { 
      detail: { name, avatar:avatar || null } 
    }));
  };

  const handleNameUpdate = async () => {
    if (!name.trim()) {
      setError('Name cannot be empty')
      return
    }

    setSaving(true)
    setError("")
    setSuccess("")

    try {
      const response = await fetch('/api/user/update', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: name.trim() })
      })

      const data = await response.json()

      if (response.ok) {
        setSuccess('Name updated successfully!')
        setUser({ ...user, name: name.trim() })
        refreshHeader()
        setTimeout(() => setSuccess(""), 3000)
      } else {
        setError(data.message || 'Failed to update name')
      }
    } catch (err) {
      setError('An error occurred while updating your name')
    } finally {
      setSaving(false)
    }
  }

  const handlePhotoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    if (file.size > 5 * 1024 * 1024) {
      setError('File size must be less than 5MB')
      return
    }

    if (!['image/jpeg', 'image/png', 'image/gif'].includes(file.type)) {
      setError('Only JPG, PNG, and GIF files are allowed')
      return
    }

    setSaving(true)
    setError("")
    setSuccess("")

    const formData = new FormData()
    formData.append('avatar', file)

    try {
      const response = await fetch('/api/user/avatar', {
        method: 'POST',
        body: formData
      })

      const data = await response.json()

      if (response.ok) {
        setAvatar(data.avatar)
        setUser({ ...user, avatar: data.avatar })
        refreshHeader()
        setSuccess('Photo updated successfully!')
        setTimeout(() => setSuccess(""), 3000)
      } else {
        setError(data.message || 'Failed to upload photo')
      }
    } catch (err) {
      setError('An error occurred while uploading your photo')
    } finally {
      setSaving(false)
    }
  }

  const handleRemovePhoto = async () => {
    setSaving(true)
    setError("")
    setSuccess("")

    try {
      const response = await fetch('/api/user/avatar', {
        method: 'DELETE'
      })

      const data = await response.json()

      if (response.ok) {
        setAvatar("")
        setUser({ ...user, avatar: "" })
        // Call refreshHeader AFTER state update with empty string
        window.dispatchEvent(new CustomEvent('userUpdated', { 
          detail: { name, avatar: null }  // Explicitly pass null
        }));
        setSuccess('Photo removed successfully!')
        setTimeout(() => setSuccess(""), 3000)
      } else {
        setError(data.message || 'Failed to remove photo')
      }
    } catch (err) {
      setError('An error occurred while removing your photo')
    } finally {
      setSaving(false)
    }
  }

  const handleDeleteAccount = async () => {
    setDeleting(true)
    setError("")

    try {
      const response = await fetch('/api/user/delete', {
        method: 'DELETE'
      })

      if (response.ok) {
        window.location.href = '/login'
      } else {
        const data = await response.json()
        setError(data.message || 'Failed to delete account')
      }
    } catch (err) {
      setError('An error occurred while deleting your account')
    } finally {
      setDeleting(false)
      setShowDeleteConfirm(false)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    )
  }

  return (
    <>
      <Header />
      <div className="min-h-screen bg-background pt-20 pb-12 px-4">
        <div className="max-w-4xl mx-auto space-y-6">
          <h1 className="text-3xl font-bold text-foreground mb-8">Account Settings</h1>

          {error && (
            <div className="bg-destructive/10 border border-destructive/20 text-destructive px-4 py-3 rounded-lg flex items-center gap-2">
              <AlertTriangle className="w-5 h-5" />
              {error}
            </div>
          )}

          {success && (
            <div className="bg-green-500/10 border border-green-500/20 text-green-600 dark:text-green-400 px-4 py-3 rounded-lg">
              {success}
            </div>
          )}

          {/* Profile Section */}
          <Card>
            <CardHeader>
              <CardTitle>Profile Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Avatar Section */}
              <div className="flex items-center gap-6">
                <div className="relative">
                  {avatar ? (
                    <img
                      src={avatar}
                      alt="Profile"
                      className="w-24 h-24 rounded-full object-cover border-2 border-border"
                    />
                  ) : (
                    <div className="w-24 h-24 rounded-full bg-primary/10 flex items-center justify-center border-2 border-border">
                      <User className="w-12 h-12 text-primary" />
                    </div>
                  )}
                </div>
                <div className="space-y-2">
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/jpeg,image/png,image/gif"
                    onChange={handlePhotoUpload}
                    className="hidden"
                  />
                  <Button
                    onClick={() => fileInputRef.current?.click()}
                    disabled={saving}
                    variant="outline"
                    size="sm"
                    className="gap-2"
                  >
                    <Camera className="w-4 h-4" />
                    Change Photo
                  </Button>
                  {avatar && (
                    <Button
                      onClick={handleRemovePhoto}
                      disabled={saving}
                      variant="outline"
                      size="sm"
                      className="gap-2 ml-2"
                    >
                      <Trash2 className="w-4 h-4" />
                      Remove Photo
                    </Button>
                  )}
                  <p className="text-xs text-muted-foreground">
                    JPG, PNG or GIF. Max 5MB.
                  </p>
                </div>
              </div>

              {/* Name Field */}
              <div className="space-y-2">
                <label className="text-sm font-medium flex items-center gap-2">
                  <User className="w-4 h-4" />
                  Full Name
                </label>
                <div className="flex gap-2">
                  <Input
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="Your name"
                    className="flex-1"
                  />
                  <Button
                    onClick={handleNameUpdate}
                    disabled={saving || name === user?.name}
                    className="gap-2"
                  >
                    <Save className="w-4 h-4" />
                    Save
                  </Button>
                </div>
              </div>

              {/* Email Field (Read-only) */}
              <div className="space-y-2">
                <label className="text-sm font-medium flex items-center gap-2">
                  <Mail className="w-4 h-4" />
                  Email Address
                </label>
                <Input
                  value={user?.email || ""}
                  disabled
                  className="bg-muted"
                />
                <p className="text-xs text-muted-foreground">
                  Email cannot be changed
                </p>
              </div>

              {/* Provider Info */}
              <div className="pt-4 border-t border-border">
                <p className="text-sm text-muted-foreground">
                  Account Type: <span className="font-medium text-foreground capitalize">{user?.provider || "Local"}</span>
                </p>
              </div>
            </CardContent>
          </Card>

          {/* FAQs Section */}
          <Card>
            <CardHeader>
              <CardTitle>Frequently Asked Questions</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {faqs.map((faq, index) => (
                <div key={index} className="border border-border rounded-lg">
                  <button
                    onClick={() => setExpandedFaq(expandedFaq === index ? null : index)}
                    className="w-full flex items-center justify-between p-4 text-left hover:bg-accent/50 transition-colors rounded-lg"
                  >
                    <span className="font-medium text-foreground">{faq.question}</span>
                    {expandedFaq === index ? (
                      <ChevronUp className="w-5 h-5 text-muted-foreground" />
                    ) : (
                      <ChevronDown className="w-5 h-5 text-muted-foreground" />
                    )}
                  </button>
                  {expandedFaq === index && (
                    <div className="px-4 pb-4 text-sm text-muted-foreground">
                      {faq.answer}
                    </div>
                  )}
                </div>
              ))}
            </CardContent>
          </Card>

          {/* Danger Zone */}
          <Card className="border-destructive/50">
            <CardHeader>
              <CardTitle className="text-destructive">Danger Zone</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <p className="text-sm text-muted-foreground">
                  Once you delete your account, there is no going back. Please be certain.
                </p>
                <Button
                  onClick={() => setShowDeleteConfirm(true)}
                  variant="destructive"
                  className="gap-2"
                >
                  <Trash2 className="w-4 h-4" />
                  Delete Account
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Delete Confirmation Modal */}
      {showDeleteConfirm && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-[100] flex items-center justify-center p-4">
          <div className="bg-card border border-destructive rounded-lg shadow-2xl max-w-md w-full p-6 space-y-4">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-full bg-destructive/10 flex items-center justify-center">
                <AlertTriangle className="w-6 h-6 text-destructive" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-foreground">Delete Account</h3>
                <p className="text-sm text-muted-foreground">This action cannot be undone</p>
              </div>
            </div>

            <p className="text-sm text-muted-foreground border-l-2 border-destructive pl-4">
              All your data, including saved analyses and settings, will be permanently deleted. Are you absolutely sure?
            </p>

            <div className="flex gap-3 pt-2">
              <Button
                variant="outline"
                onClick={() => setShowDeleteConfirm(false)}
                disabled={deleting}
                className="flex-1"
              >
                <X className="w-4 h-4 mr-2" />
                Cancel
              </Button>
              <Button
                variant="destructive"
                onClick={handleDeleteAccount}
                disabled={deleting}
                className="flex-1"
              >
                {deleting ? (
                  <>
                    <span className="animate-spin mr-2">⏳</span>
                    Deleting...
                  </>
                ) : (
                  <>
                    <Trash2 className="w-4 h-4 mr-2" />
                    Delete Forever
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}